#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Backup sources & data
ynh_backup "/opt/$app" "sources" # TODO: adapter

# Copy NGINX configuration
domain=$(ynh_app_setting_get "$app" domain)
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"

# Copy Gunicorn pool configuration
ynh_backup "/etc/systemd/system/$app.service" "gunicorn.service"
