#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


app=$YNH_APP_INSTANCE_NAME

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
# email=$YNH_APP_ARG_EMAIL

final_path=/opt/$app

ynh_clean_setup () {
    ynh_print_info "Cleaning the aborted install. You may want to unistall dependencies also."
    sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
    sudo systemctl nginx reload
    sudo yunohost service remove $app
    sudo rm -f /etc/systemd/system/$app.service
    sudo systemctl daemon-reload
    sudo userdel $app
    sudo rm -Rf $final_path
}

ynh_abort_if_errors



# Check if admin exists
ynh_user_exists $admin \
    || ynh_die "Wrong admin"

ynh_app_setting_set "$app" admin "$admin"
# ynh_app_setting_set "$app" email "$email"

secret=$(ynh_string_random 24) # A bug don't allow to do random string bigger than 24
ynh_app_setting_set "$app" secret "$secret"

# FIXME: crash si le path est ≠ « / »
# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Dependencies
ynh_install_app_dependencies $pkg_dependencies

sudo mkdir -p $final_path
sudo git clone $app_repo $final_path
app_path=$final_path/app

python3 -m venv  $final_path/venv
venv_python='$final_path/venv/bin/python3'
venv_pip='$final_path/venv/bin/pip'
# PyMySQL → cryptography → setuptools>=18.5
# Required on Jessie, Stretch has setuptools>=18.5
# venv_pip install 'setuptools>=18.5'

$venv_pip install gunicorn
$venv_pip install -r $app_path/requirements.txt

# Configuration Django
ynh_replace_string "YNH_APP_ARG_ADMIN" $admin $app_path/local_settings.py
ynh_replace_string "YNH_APP_ARG_DOMAIN" $domain $app_path/local_settings.py
ynh_replace_string "YNH_APP_ARG_PATH" $path $app_path/local_settings.py
ynh_replace_string "YNH_APP_SECRET_KEY" $secret $app_path/local_settings.py
ynh_replace_string "YNH_APP_STATIC_ROOT" $secret $final_path/static $app_path/local_settings.py

# Set permissions
sudo useradd $app -d $final_path || ynh_die "User already exists: ${app}"
sudo chown -R $app:www-data $final_path

sudo yunohost app addaccess $app -u $admin


# Log folder
sudo mkdir -p /var/log/$app
sudo chown -R $app /var/log/$app
sudo chgrp -R www-data /var/log/$app


sudo -u $app $venv_python $app_path/manage.py migrate --noinput
sudo -u $app $venv_python $app_path/manage.py collectstatic --noinput
# QUESTION: où_collectstatic dépose-t-il ses fichiers ?


# Modify Nginx configuration file and copy it to Nginx conf directory
ynh_replace_string "PATHTOCHANGE" $path ../conf/nginx.conf
ynh_replace_string "YNH_APP_INSTANCE_NAME" $app ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf


# Service gunicorn
ynh_replace_string "YNH_APP_INSTANCE_NAME" $app ../conf/gunicorn_config.py
ynh_replace_string "YNH_APP_INSTANCE_NAME" $app ../conf/gunicorn.service
sudo cp ../conf/gunicorn.service /etc/systemd/system/$app.service
sudo systemctl daemon-reload
sudo cp ../conf/gunicorn_config.py /opt/$app/


## Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo systemctl start $app
sudo systemctl enable $app
sudo yunohost service add $app -l /var/log/gunicorn/$app.log


# C'est public ! (pas de SSO ynh)
ynh_app_setting_set "$app" skipped_uris "/"
sudo yunohost app ssowatconf
