#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
sudo rm -Rf /opt/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

sudo service $app stop
sudo killall $app
sudo yunohost service remove $app
sudo rm -f /etc/systemd/system/$app.service
sudo systemctl daemon-reload
sudo service nginx reload
sudo yunohost app ssowatconf
sudo userdel $app
